apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: minio
  name: minio
spec:
  replicas: 1
  minReadySeconds: 10
  serviceName: minio-svc
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
    spec:
      containers:
        - args:
            - server
            - --console-address
            - :9210
            - --address
            - :9209
            - /data
          env:
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-creds
                  key: password
                  optional: false
            - name: MINIO_ROOT_USER
              value: admin
          image: minio/minio
          name: minio
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: minio-pvc
      hostname: minio1
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: minio-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: local-path
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: minio
  name: minio-svc
spec:
  ports:
    - name: "9209"
      port: 9209
      targetPort: 9209
    - name: "9210"
      port: 9210
      targetPort: 9210
  selector:
    app.kubernetes.io/name: minio
  externalIPs: [ "x.x.x.x" ]
  type: NodePort
