apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/name: mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "5.0.9"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: aitools
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: db-user-password
      roles:
        # - name: clusterAdmin
        #   db: admin
        # - name: userAdminAnyDatabase
        #   db: admin
        - name: root # should be corrected
          db: admin
      scramCredentialsSecretName: my-scram
  statefulSet:
    spec:
        # Name for the service object created by the operator
      serviceName: mongo-svc
      selector: {}
        # Specifies a size for the data volume different from the default 10Gi
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: local-path
            resources:
              requests:
                storage: 10Gi
        - metadata:
            name: logs-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: local-path
            resources:
              requests:
                storage: 1Gi
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
